# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c1c49fef8c9673e0b48da64002d32a4eb12911ea4d9e36663d825c1b7d704d4cda1b5108b24e37097fea2fdd71d229af3f99aec9d8b08b3f75645aae2d38381

test:
  secret_key_base: 624ed2856f92acfbe8104be04323872c9ad250870eb1dfe64921f62eca723b89412fecd33ac8faafa3eb25e7c88dc71997f6907765b83e8d7da7a89922c7254c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
